-- phpMyAdmin SQL Dump
-- version 5.2.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Aug 03, 2026 at 03:02 PM
-- Server version: 8.0.45-cll-lve
-- PHP Version: 8.1.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ciopakch_admin`
--

-- --------------------------------------------------------

--
-- Table structure for table `doctor_detail`
--

CREATE TABLE `doctor_detail` (
  `dr_id` int NOT NULL,
  `dr_name` varchar(255) DEFAULT NULL,
  `dr_department` varchar(255) DEFAULT NULL,
  `dr_record1` varchar(255) DEFAULT NULL,
  `dr_record2` varchar(255) DEFAULT NULL,
  `dr_record3` varchar(255) DEFAULT NULL,
  `dr_record4` varchar(255) DEFAULT NULL,
  `dr_record5` varchar(255) DEFAULT NULL,
  `dr_record6` varchar(255) DEFAULT NULL,
  `dr_record7` varchar(255) DEFAULT NULL,
  `dr_record8` varchar(255) DEFAULT NULL,
  `dr_record9` varchar(255) DEFAULT NULL,
  `dr_record10` varchar(255) DEFAULT NULL,
  `educational_record1` varchar(255) DEFAULT NULL,
  `educational_record2` varchar(255) DEFAULT NULL,
  `educational_record3` varchar(255) DEFAULT NULL,
  `educational_record4` varchar(255) DEFAULT NULL,
  `educational_record5` varchar(255) DEFAULT NULL,
  `educational_record6` varchar(255) DEFAULT NULL,
  `educational_record7` varchar(255) DEFAULT NULL,
  `educational_record8` varchar(255) DEFAULT NULL,
  `educational_record9` varchar(255) DEFAULT NULL,
  `educational_record10` varchar(255) DEFAULT NULL,
  `position1` varchar(255) DEFAULT NULL,
  `position2` varchar(255) DEFAULT NULL,
  `position3` varchar(255) DEFAULT NULL,
  `position4` varchar(255) DEFAULT NULL,
  `position5` varchar(255) DEFAULT NULL,
  `contribution1` varchar(255) DEFAULT NULL,
  `contribution2` varchar(255) DEFAULT NULL,
  `contribution3` varchar(255) DEFAULT NULL,
  `contribution4` varchar(255) DEFAULT NULL,
  `contribution5` varchar(255) DEFAULT NULL,
  `contribution_link` varchar(255) DEFAULT NULL,
  `contribution_file` varchar(255) DEFAULT NULL,
  `dr_check1` varchar(255) DEFAULT NULL,
  `dr_check2` varchar(255) DEFAULT NULL,
  `dr_check3` varchar(255) DEFAULT NULL,
  `dr_img` varchar(255) DEFAULT NULL,
  `date_add` datetime DEFAULT NULL,
  `user_add` varchar(255) DEFAULT NULL,
  `edit_date` datetime DEFAULT NULL,
  `edit_user` varchar(255) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=tis620 ROW_FORMAT=DYNAMIC;

--
-- Dumping data for table `doctor_detail`
--

INSERT INTO `doctor_detail` (`dr_id`, `dr_name`, `dr_department`, `dr_record1`, `dr_record2`, `dr_record3`, `dr_record4`, `dr_record5`, `dr_record6`, `dr_record7`, `dr_record8`, `dr_record9`, `dr_record10`, `educational_record1`, `educational_record2`, `educational_record3`, `educational_record4`, `educational_record5`, `educational_record6`, `educational_record7`, `educational_record8`, `educational_record9`, `educational_record10`, `position1`, `position2`, `position3`, `position4`, `position5`, `contribution1`, `contribution2`, `contribution3`, `contribution4`, `contribution5`, `contribution_link`, `contribution_file`, `dr_check1`, `dr_check2`, `dr_check3`, `dr_img`, `date_add`, `user_add`, `edit_date`, `edit_user`) VALUES
(101, 'นพ.บุญชัย กิ่งเพ็ชรรุ่งเรือง', 'สูติ-นรีเวชกรรม', 'นายแพทย์ชำนาญการพิเศษ', 'วุฒิบัตรสาขาสูติศาสตร์-นรีเวชวิทยา', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'นรีเวช วันอังคาร เวลา 08.00 - 16.00 น.', 'ฝากครรภ์ วันศุกร์ เวลา 08.00 - 16.00 น.', '', 'dr_im/BunchaiV1.jpg', '2022-11-24 11:36:50', 'admin', '2023-12-27 14:34:20', 'admin'),
(102, 'พญ.ปนัดดา เขมรัตน์ตระกูล', 'สูติ-นรีเวชกรรม', 'วุฒิบัตรสาขาสูติศาสตร์-นรีเวชวิทยา', '', '', '', '', '', '', '', '', '', '1989 - 1995 - Faculty of Medicine Siriraj Hospital, Mahidol University, Bangkok, Thailand (Doctor of medicine)', '1998 - 2001 - Obstetrics and gynecology , Mahidol University', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการพิเศษ', 'รองผู้อำนวยการกลุ่มภารกิจด้านบริการทุติยภูมิและตติยภูมิ', '', '', '', '', '', '', '', '', '', '', 'นรีเวช วันพุธ เวลา 08.00 - 16.00 น.', 'ฝากครรภ์ วันอังคาร 08.00 - 16.00 น.', '', 'dr_im/PanadV2.jpg', '2022-11-24 11:46:59', 'admin', '2023-04-20 11:39:08', 'admin'),
(103, 'พญ.ธัญญารัตน์ วินิจธนา', 'สูติ-นรีเวชกรรม', 'นายแพทย์ชำนาญการพิเศษ', 'วุฒิบัตรสาขาสูติศาสตร์-นรีเวชวิทยา', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'นรีเวช วันศุกร์ เวลา 08.00 - 16.00 น.', 'ฝากครรภ์ วันพฤหัส เวลา 08.00 - 16.00 น.', '', 'dr_im/TanyaV1.jpg', '2022-11-24 11:48:16', 'admin', '2023-04-20 11:00:51', 'admin'),
(104, 'นพ.ธนกร วรินทร์', 'สูติ-นรีเวชกรรม', 'นายแพทย์ชำนาญการ', 'วุฒิบัตรสาขาสูติศาสตร์-นรีเวชวิทยา', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นรีเวช วันพฤหัสบดี เวลา 08.00 - 16.00 น.', 'ฝากครรภ์ วันพุธ เวลา 08.00 - 16.00 น.', '', 'dr_im/TanakV1.jpg', '2022-11-24 11:48:50', 'admin', '2022-11-25 15:50:51', 'admin'),
(105, 'พญ.ขนิษฐา  ปานสำเนียง', 'สูติ-นรีเวชกรรม', 'วุฒิบัตรสาขาสูติศาสตร์-นรีเวชวิทยา', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการ', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'dr_im/KanitV1.jpg', '2025-08-28 09:39:59', 'องกรแพทย์', '2025-08-28 09:44:17', 'องกรแพทย์'),
(106, 'พญ.วริศรา ราชพล', 'สูติ-นรีเวชกรรม', 'วุฒิบัตรสาขาสูติศาสตร์ นรีเวชวิทยา', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2012-2019 แพทยศาสตร์บัณฑิต เกียรตินิยมอันดับ2 มหาวิทยาลัยเทคโนโลยีสุรนารี', '2022-2024 วุฒิบัตรสาขาสูติศาสตร์ นรีเวชวิทยา รพ.ศรีนครินทร์ มหาวิทยาลัยขอนแก่น', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/WarisV1.jpg', '2025-10-03 16:29:21', 'admin', NULL, NULL),
(201, 'นพ.สมยศ สุขเสถียร', 'ศัลยกรรมทั่วไป', 'นายแพทย์ชำนาญการพิเศษ', 'วุฒิบัตรสาขาศัลยศาสตร์', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์   เวลา 08.00 - 16.00 น.', 'วันศุกร์     เวลา 08.00 - 12.00 น.', '', 'dr_im/SomyV1.jpg', '2022-11-24 11:53:31', 'admin', '2022-11-24 13:31:47', 'admin'),
(202, 'นพ.ธเนศ สันติโรจนกุล', 'ศัลยกรรมทั่วไป', 'นายแพทย์ชำนาญการ', 'วุฒิบัตรสาขาศัลยศาสตร์', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันอังคาร  เวลา 08.00 - 16.00 น.', 'วันพฤหัสบดี  เวลา 08.00 - 12.00 น.', '', 'dr_im/TanetV1.jpg', '2022-11-24 11:56:00', 'admin', '2022-11-24 13:31:57', 'admin'),
(203, 'พญ.จิตรานันท์ นาคหมื่นไวย', 'ศัลยกรรมทั่วไป', 'นายแพทย์ปฏิบัติการ', 'วุฒิบัตรสาขาศัลยศาสตร์', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์  เวลา 08.00 - 12.00 น.', 'วันพุธ  เวลา 08.00 - 16.00 น.', '', 'dr_im/JitraV1.jpg', '2022-11-24 13:25:40', 'admin', '2022-11-24 16:10:58', 'admin'),
(204, 'นพ.ชาคริต ศรีเจริญวณิชย์', 'ศัลยกรรมทั่วไป', 'Transoral Endoscopic Thyroidectomy Vestibular Approach (TOETVA)', 'Laparoscopic Cholecystectomy', 'Laparoscopic Hernia Repair (TEP, TAPP)', 'Laparoscopic Colorectal Surgery', 'Endoscopic Surgery (EGD, Colonoscopy, ERCP, advance endoscopy)', '', '', '', '', '', '2005-2011 - Faculty of Medicine Siriraj Hospital, Mahidol University, Bangkok, Thailand (Doctor of medicine)', '2012-2016 - Residency training in General Surgery, Rajavithi Hospital, Bangkok, Thailand (Diploma in Thai board of General Surgery)', '2019-2021 clinical fellowship in minimally invasive surgery and endocrinology surgery, Police General Hospital, Thailand', '2012- Advanced Cardiac Life Support (ACLS), Bangkok, Thailand', '2012- Advanced Trauma Life Support (ATLS) Student Course Bangkok, Thailand', '', '', '', '', '', 'นายแพทย์ชำนาญการ', 'รองผู้อำนวยการฝ่ายกิจกรรมพิเศษ', 'ผู้ช่วยผู้อำนวยการด้านบริการ (service plan)', '', '', '', '', '', '', '', '', '', 'วันพุธ  เวลา 08.00 - 12.00 น.', 'วันศุกร์  เวลา 08.00 - 16.00 น.', '', 'dr_im/ChakritV1.jpg', '2022-11-24 13:27:29', 'admin', '2022-11-30 16:35:32', 'admin'),
(205, 'นพ.ศศิภาพ  วีระสมบัติ', 'ศัลยกรรมทั่วไป', 'วุฒิบัตรสาขาศัลยศาสตร์', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการ', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'dr_im/SasiV1.jpg', '2025-08-28 09:46:10', 'องกรแพทย์', NULL, NULL),
(301, 'นพ.ฉายฉันท์ สร้อยศรีทอง', 'ศัลยกรรมยูโรวิทยา', 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpic.jpg', '2025-10-04 11:54:16', 'admin', NULL, NULL),
(302, 'นพ.ธนวินท์ โชติเรืองประเสริฐ', 'ศัลยกรรมยูโรวิทยา', 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/TanawV1.jpg', '2025-10-04 11:56:30', 'admin', NULL, NULL),
(401, 'นพ.ปิยะพงษ์ ชินคำอัครพัฒน์', 'ศัลยศาสตร์ออร์โธปิดิกส์', 'ผ่าตัดข้อเทียม (เข่าและสะโพก )', 'ผ่าตัดส่องกล้อง  @ เข่า ไหล่ ข้อศอก ข้อเท้า กระดูกสันหลัง (one portal) ', 'ผ่าตัดกระดูกสันหลัง (ระดับเอว )', 'ผ่าตัดกระดูกหัก (ทั่วไป)', '', '', '', '', '', '', '2021 : Diploma in Clinical Statistics , Center for Clinical Epidermiology & Clinical Statistics, Faculty of Medicine Chiang Mai University ', '2020 : Diploma in Clinical Epidermiology,  Institute of Medicine , Suranaree University of Technology & Clinical Epidermiology Society 2020 : หนังสืออนุมัติแสดงความรู้ความชำนาญในการประกอบวิชาชีพเวชกรรมสาขาเวชศาสตร์ป้องกัน แขนงสาธารณสุขศาสตร์', '2018 : หลักสูตรนักบริหารระดับสูงด้านสาธารณสุข (นบส.ส.) รุ่นที่ 25 สถาบันพัฒนาสุขภาพอาเซียน มหาวิทยาลัยมหิดล 2018 :  หลักสูตรนักพัฒนบริหารศาสตร์ระดับกลาง รุ่นที่ 3 สถาบันบัณฑิตพัฒนบริหารศาสตร์', '2016 : Spine surgery. Department of orthopaedics and traumatology, university of Hongkong, February- March', '2015 :  Full-endoscopic Operations of the spine training program Bumrungrad International Hospital (2days).', '2014 : Endoprosthesis joint replacement. Surgical exchange and training program .Rotenberg ,Germany. October', '2012 : THA&TKA and navigated systems . Fellowship, St. Vincenz Hospital, Brakel, Germany. July ? August.', '2010 : Shoulder Arthroscopy. Clinician and  Investigator ,Kyung Hee University ,Seoul ,Korea. November.', '2009 : Sports medicine. Guest fellow , Technical University of Munich ,Germany. , May ? July 2009.', '2008 :  Clinical and operative orthopaedic surgery, AO Fellowship , Tubingen ,Germany. July ? August 2008.', 'นายแพทย์เชี่ยวชาญ (C9)', 'รองผู้อำนวยการ ด้านการเงินและการคลัง (CFO)', 'Chief of Orthopaedic Unit, Pakchongnana  Hospital.', '', '', 'Comparative treatment between open reduction and close reduction technique in close supracondylar humeral fracture (Gartland III). Saraburi hospital medical journal 2006; 31(2): 87-91.', 'Health behavior improvement program leads to an increase in the knee scores in OA knee. Journal of health science 2014; 23: 437-44.', 'Nail fixation versus clavicle support for displaced mid shaft clavicle fractures: time to return to work and long term results. Journal of the medical association of Thailand 2018; 101(suppl3): s195-202.', 'Heterotopic ossification following non cemented hip replacement: a comparative study using minimal invasive surgery vs. conventional anterolateral approach. Journal of southeast asian medical research 2019; 3(1): 18-24.', '', '', '', 'วันอังคาร เวลา 09.00 - 15.30 น.', 'วันพฤหัสบดี  เวลา 09 .00 - 11.30 น.', '', 'dr_im/PiyaV1.jpg', '2022-11-24 13:31:22', 'admin', '2024-01-16 16:14:19', 'องกรแพทย์'),
(402, 'นพ.ขวัญชัย มาสุธน', 'ศัลยศาสตร์ออร์โธปิดิกส์', 'นายแพทย์ชำนาญการ', 'วุฒิบัตรสาขาศัลยศาสตร์ออร์โธปิดิกส์', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'วันจันทร์  เวลา 09.00 - 11.30 น.', 'วันพุธ  เวลา 09.00 - 15.30 น.', '', 'dr_im/KwanV1.jpg', '2022-11-24 14:24:31', 'admin', '2022-11-29 15:17:33', 'admin'),
(403, 'นพ.ศุภวิชญ์ จุฬาปกรณ์', 'ศัลยศาสตร์ออร์โธปิดิกส์', 'วุฒิบัตรสาขาศัลยศาสตร์ออร์โธปิดิกส์', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการพิเศษ', '', '', '', '', '', '', '', '', '', '', '', 'วันจันทร์ เวลา 09.00 - 15.30 น.', 'วันพุธ  เวลา 09.00 - 11.30 น.', '', 'dr_im/SupaV1.jpg', '2022-11-24 14:27:50', 'admin', '2022-11-30 16:30:21', 'admin'),
(404, 'นพ.จิรายุ เชาวลิตวงศ์', 'ศัลยศาสตร์ออร์โธปิดิกส์', 'นายแพทย์ชำนาญการ', 'วุฒิบัตรสาขาศัลยศาสตร์ออร์โธปิดิกส์', 'อนุสาขาการผ่าตัดกระดูกสันหลัง', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'วันอังคาร เวลา 09.00 - 11.30 น.', 'วันพฤหัสบดี  เวลา 09.00 - 15.30 น.', '', 'dr_im/nonpic.jpg', '2022-11-24 14:29:17', 'admin', '2022-11-29 15:18:41', 'admin'),
(405, 'นพ.ชาญชัย จงทวีสถาพร', 'ศัลยศาสตร์ออร์โธปิดิกส์', 'วุฒิบัตรสาขาศัลยศาสตร์ออร์โธปิดิกส์', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/ChanV1.jpg', '2025-10-04 16:43:26', 'admin', NULL, NULL),
(501, 'นพ.วุฒิพงษ์ อัศวเพชรกูล', 'อายุรกรรม', 'วุฒิบัตรสาขาอายุรศาสตร์', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการพิเศษ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/VutiV1.jpg', '2025-10-09 10:58:10', 'admin', NULL, NULL),
(502, 'พญ.รจิตา หาญตะล่อม', 'อายุรกรรม', '', 'วุฒิบัตรสาขาอายุรศาสตร์', 'วุฒิบัตรสาขาอายุรศาสตร์โรคไต', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์เชี่ยวชาญ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์ - วันศุกร์ เวลา 08.00 - 16.00 น.', '', '', 'dr_im/RajiV1.jpg', '2022-11-24 14:36:49', 'admin', '2022-11-24 15:11:34', 'admin'),
(503, 'พญ.เกษศรินทร์ กาญจนจารุรัตน์', 'อายุรกรรม', '', 'วุฒิบัตรสาขาอายุรศาสตร์', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์ - วันศุกร์ เวลา 08.00 - 16.00 น.', '', '', 'dr_im/GezV1.jpg', '2022-11-24 14:39:19', 'admin', '2022-11-24 15:28:18', 'admin'),
(504, 'พญ.ปภาดา ศรีเมฆ', 'อายุรกรรม', '', 'วุฒิบัตรสาขาอายุรศาสตร์', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์ - วันศุกร์ เวลา 08.00 - 16.00 น.', '', '', 'dr_im/PapadaV1.jpg', '2022-11-24 14:40:37', 'admin', NULL, NULL),
(505, 'พญ.วรรณภา รักสุจริต', 'อายุรกรรม', 'วุฒิบัตรสาขาอายุรศาสตร์', 'วุฒิบัตรสาขาประสาทวิทยา', '', '', '', '', '', '', '', '', 'แพทยศาสตร์บัณฑิต มหาวิทยาลัยศรีนครินทรวิโรฒ', '', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการ', '', '', '', '', '', '', '', '', '', '', '', 'วันจันทร์ - วันศุกร์ เวลา 08.00 - 16.00 น.', 'คลินิกพิเศษเฉพาะทางนอกเวลาราชการ เวลา 16.00 - 20.00 น.', '', 'dr_im/WannapaV1.jpg', '2022-11-24 15:08:43', 'admin', '2023-08-31 15:50:24', 'admin'),
(506, 'พญ.วรัมพร ศิลปะ', 'อายุรกรรม', '', 'วุฒิบัตรสาขาอายุรศาสตร์', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์ - วันศุกร์ เวลา 08.00 - 16.00 น.', '', '', 'dr_im/WarumV1.jpg', '2022-11-24 15:09:44', 'admin', '2022-11-24 16:12:19', 'admin'),
(507, 'นพ.ปุณณวิช จิตเจือจุน', 'อายุรกรรม', '', 'วุฒิบัตรสาขาอายุรศาสตร์', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการ', '', '', '', '', '', '', '', '', '', '', '', 'วันจันทร์ - วันศุกร์ เวลา 08.00 - 16.00 น.', 'คลินิกพิเศษเฉพาะทางนอกเวลาราชการ เวลา 16.00 - 20.00 น.', '', 'dr_im/PunnaV1.jpg', '2022-11-24 15:11:18', 'admin', '2022-12-27 15:43:25', 'admin'),
(508, 'นพ.กรภพ นาคพันธุ์', 'อายุรกรรม', 'วุฒิบัตรสาขาอายุรศาสตร์', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ฏิบัติการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/GorraV1.jpg', '2025-10-04 19:22:38', 'admin', NULL, NULL),
(601, 'นพ.สมศักดิ์ สหสิทธิวัฒน์', 'กุมารเวชกรรม', '', 'วุฒิบัตรสาขากุมารเวชศาสตร์', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการพิเศษ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันพฤหัสบดี เวลา 08.00 - 16.00 น.', 'วันศุกร์     เวลา 08.00 - 16.00 น.', '', 'dr_im/SomsakV1.jpg', '2022-11-24 15:15:30', 'admin', NULL, NULL),
(602, 'นพ.วารสินทร์ จันทร์ประกายสี', 'กุมารเวชกรรม', '', 'วุฒิบัตรสาขากุมารเวชศาสตร์', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์เชี่ยวชาญ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์  เวลา 08.00 - 16.00 น.', 'วันศุกร์     เวลา 08.00 - 16.00 น.', '', 'dr_im/WaraV1.jpg', '2022-11-24 15:19:34', 'admin', NULL, NULL),
(603, 'พญ.ณัฐฑิณี นภัทรธีรโชติ', 'กุมารเวชกรรม', '', 'วุฒิบัตรสาขากุมารเวชศาสตร์', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันพฤหัสบดี เวลา 08.00 - 16.00 น.', 'วันศุกร์  เวลา 08.00 - 16.00 น.', '', 'dr_im/NaddiV1.jpg', '2022-11-24 15:21:04', 'admin', '2022-11-24 15:22:31', 'admin'),
(604, 'พญ.กุลฤดี ศิริพรโภคา', 'กุมารเวชกรรม', '', 'วุฒิบัตรสาขากุมารเวชศาสตร์', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการ', '', '', '', '', '', '', '', '', '', '', '', 'วันพฤหัสบดี เวลา 08.00 - 16.00 น.', 'วันศุกร์     เวลา 08.00 - 16.00 น.', '', 'dr_im/GulV1.jpg', '2022-11-24 15:22:07', 'admin', '2023-12-27 14:41:54', 'admin'),
(605, 'พญ.วัชรินทร์ คล้ายทอง', 'กุมารเวชกรรม', '', 'วุฒิบัตรสาขากุมารเวชศาสตร์', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์  เวลา 08.00 - 16.00 น.', 'วันอังคาร    เวลา 08.00 - 16.00 น.', '', 'dr_im/WatV1.jpg', '2022-11-24 15:23:41', 'admin', NULL, NULL),
(606, 'พญ.บัณฑิตา แสงชลินทร์', 'กุมารเวชกรรม', '', 'วุฒิบัตรสาขากุมารเวชศาสตร์', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการ', '', '', '', '', '', '', '', '', '', '', '', 'วันจันทร์  เวลา 08.00 - 16.00 น.', 'วันอังคาร  เวลา 08.00 - 16.00 น.', '', 'dr_im/BundiV1.jpg', '2022-11-24 15:24:45', 'admin', '2023-08-31 16:13:21', 'admin'),
(607, 'พญ.ศิริเกศ อัมหิรัญ', 'กุมารเวชกรรม', 'วุฒิบัตรสาขากุมารเวชศาสตร์', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpic.jpg', '2025-10-04 21:54:20', 'admin', NULL, NULL),
(608, 'พญ.พิมพ์ชนก ศิริศาสตร์', 'กุมารเวชกรรม', 'วุฒิบัตรสาขากุมารเวชศาสตร์', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/PimV1.jpg', '2025-10-04 21:55:42', 'admin', NULL, NULL),
(701, 'พญ.นิศารัตน์ จองธุระกิจ', 'จักษุ', 'วุฒิบัตรสาขาจักษุวิทยา', '', '', '', '', '', '', '', '', '', '2006 Degree of bachelor of Medicine and bachelor of Surgery . The University Of Leeds,UK', '', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการ', '', '', '', '', '', '', '', '', '', '', '', 'วันอังคาร เวลา 08.00 - 16.00 น.', 'วันพฤหัสบดี  เวลา 08.00 - 16.00 น.', '', 'dr_im/nonpicw.jpg', '2022-11-24 15:33:05', 'admin', '2023-08-31 16:15:39', 'admin'),
(702, 'พญ.ศิรภา  วชิรปรีชาพงษ์', 'จักษุ', 'วุฒิบัตรสาขาจักษุวิทยา', '', '', '', '', '', '', '', '', '', 'แพทยศาสตร์บัณฑิต (เกียรตินิยมอันดับ 2) มหาวิทยาลัยมหิดล', '', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการ', '', '', '', '', '', '', '', '', '', '', '', 'วันจันทร์  เวลา 08.00 - 16.00 น.', 'วันพุธ  เวลา 08.00 - 16.00 น.', '', 'dr_im/SiraV1.jpg', '2023-08-31 15:55:57', 'admin', '2023-08-31 16:12:07', 'admin'),
(801, 'พญ.สคราญ อโณทัยไพบูลย์', 'รังสีวิทยา', '', 'วุฒิบัตรสาขารังสีวิทยาวินิจฉัย', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการพิเศษ', '', '', '', '', '', '', '', '', '', '', '', '-', '', '', 'dr_im/SacranV1.jpg', '2022-11-24 15:36:11', 'admin', '2022-12-21 13:27:50', 'admin'),
(802, 'พญ.เบญจพร โรจนอารีย์', 'รังสีวิทยา', '', 'วุฒิบัตรสาขารังสีวิทยาทั่วไป', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการพิเศษ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-', '', '', 'dr_im/BenjaV1.jpg', '2022-11-24 15:37:08', 'admin', NULL, NULL),
(803, 'พญ.รินทร์ลภัส ลัทธศักดิ์ศิริ', 'รังสีวิทยา', 'วุฒิบัตรสาขารังสีวิทยาวินิจฉัย', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/RinV1.jpg', '2025-10-04 22:43:06', 'admin', NULL, NULL),
(804, 'พญ.วาสนา กาญจนจารุรัตน์', 'รังสีวิทยา', 'วุฒิบัตรสาขารังสีวิทยาวินิจฉัย', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/WassV1.jpg', '2025-10-04 22:44:01', 'admin', NULL, NULL),
(901, 'พญ.วฤนดา จันทร์ประกายสี', 'วิสัญญี', '', 'วุฒิบัตรสาขาวิสัญญีวิทยา', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการพิเศษ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-', '', '', 'dr_im/WarinV1.jpg', '2022-11-24 15:38:03', 'admin', NULL, NULL),
(902, 'พญ.ศิวพร ศิริมาศรังษี', 'วิสัญญี', '', 'วุฒิบัตรสาขาวิสัญญีวิทยา', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการพิเศษ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-', '', '', 'dr_im/SiwapV1.jpg', '2022-11-24 15:38:30', 'admin', NULL, NULL),
(903, 'นพ.กิติคุณ ภูมิโคกรักษ์', 'วิสัญญี', '', 'วุฒิบัตรสาขาวิสัญญีวิทยา', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-', '', '', 'dr_im/KittiV1.jpg', '2022-11-24 15:39:02', 'admin', NULL, NULL),
(904, 'พญ.พรพรหม สิทธิเวทยานนท์', 'วิสัญญี', 'วุฒิบัตรสาขาวิสัญญีวิทยา', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpicw.jpg', '2025-10-04 23:05:02', 'admin', NULL, NULL),
(1001, 'พญ.วีรุฒา โอชา', 'เวชศาสตร์ฟื้นฟู', '', 'วุฒิบัตรสาขาเวชศาสตร์ฟื้นฟู', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์ เวลา 09.00 - 12.00 น.', 'วันศุกร์     เวลา 09.00 - 12.00 น.', '', 'dr_im/WeruV1.jpg', '2022-11-24 15:42:56', 'admin', NULL, NULL),
(1002, 'นพ.ชยุตพล ทองศิริ', 'เวชศาสตร์ฟื้นฟู', 'วุฒิบัตรสาขาเวชศาสตร์ฟื้นฟู', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/ChayutV1.jpg', '2025-10-04 23:15:55', 'admin', NULL, NULL),
(1101, 'นพ.ควรคิดณัฐฐา อรุณศรี', 'จิตเวชศาสตร์', 'วุฒิบัตรสาขาจิตเวชศาสตร์', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการพิเศษ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/KKV1.jpg', '2025-10-04 23:31:40', 'admin', NULL, NULL),
(1102, 'พญ.ปารัช ภิรมย์รัตน์', 'จิตเวชศาสตร์', 'วุฒิบัตรสาขาจิตเวชศาสตร์เด็กและวัยรุ่น', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/ParusV1.jpg', '2025-10-04 23:33:20', 'admin', NULL, NULL),
(1201, 'นพ.พิพัฒน์ แจ่มพัฒนกิจ', 'หู คอ จมูก', '', 'วุฒิบัตรสาขาโสต ศอ นาสิก วิทยา', 'อนุมัติบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการพิเศษ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์  เวลา 08.00 - 16.00 น.', 'วันพุธ     เวลา 08.00 - 16.00 น.', '', 'dr_im/PipatV1.jpg', '2022-11-24 15:28:01', 'admin', '2022-11-24 16:12:40', 'admin'),
(1202, 'พญ.พิชญาภัจณ์ มองเพ็ชร์', 'หู คอ จมูก', '', 'วุฒิบัตรสาขาโสต ศอ นาสิก วิทยา', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการ', '', '', '', '', '', '', '', '', '', '', '', 'วันอังคาร เวลา 08.00 - 16.00 น.', NULL, NULL, 'dr_im/PichayV1.jpg', '2022-11-24 15:30:33', 'admin', '2022-11-29 14:54:38', 'admin'),
(1203, 'พญ.ฐิติมา หมื่นแสน', 'หู คอ จมูก', '', 'วุฒิบัตรสาขาโสต ศอ นาสิก วิทยา', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันพฤหัสบดี เวลา 08.00 - 16.00 น.', '', '', 'dr_im/TmV1.jpg', '2022-11-24 15:29:34', 'admin', NULL, NULL),
(1301, 'พญ.ณิชกานต์ พินิจจิตรสมุทร', 'เวชศาสตร์ฉุกเฉิน', '', 'วุฒิบัตรสาขาเวชศาสตร์ฉุกเฉิน', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการ', '', '', '', '', '', '', '', '', '', '', '', 'วันจันทร์ - วันศุกร์ เวลา 08.00 - 16.00 น.', '', '', 'dr_im/NichaV1.jpg', '2022-11-24 15:57:08', 'admin', '2022-12-27 16:09:33', 'admin'),
(1302, 'พญ.วรนิษฐ์ ทวีสินธนกิตติ์', 'เวชศาสตร์ฉุกเฉิน', 'วุฒิบัตรสาขาเวชศาสตร์ฉุกเฉิน', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpicw.jpg', '2025-10-04 23:59:51', 'admin', NULL, NULL),
(1303, 'นพ.ยอดมงคล นวฤทธิอัศวิน', 'เวชศาสตร์ฉุกเฉิน', 'วุฒิบัตรสาขาเวชศาสตร์ฉุกเฉิน', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpic.jpg', '2025-10-05 00:00:33', 'admin', NULL, NULL),
(1304, 'นพ.กันตวัฒน์ ลีปายะคุณ', 'เวชศาสตร์ฉุกเฉิน', 'วุฒิบัตรสาขาเวชศาสตร์ฉุกเฉิน', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/GuntaV1.jpg', '2025-10-05 00:01:08', 'admin', NULL, NULL),
(1401, 'นพ.อดิศักดิ์ ศรีศุภรางค์กุล', 'เวชศาสตร์ครอบครัว', '', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการพิเศษ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์ - วันศุกร์ เวลา 08.00 - 16.00 น.', '', '', 'dr_im/AdisV1.jpg', '2022-11-24 16:01:22', 'admin', NULL, NULL),
(1402, 'พญ.สุจริต สุขเวสพงษ์', 'เวชศาสตร์ครอบครัว', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์เชี่ยวชาญ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpicw.jpg', '2025-10-09 10:27:44', 'admin', NULL, NULL),
(1403, 'พญ.วีณา มงคลพร', 'เวชศาสตร์ครอบครัว', '', 'วุฒิบัตรสาขากุมารเวชศาสตร์', 'อนุมัติบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์เชี่ยวชาญ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์ - วันศุกร์ เวลา 08.00 - 16.00 น.', '', '', 'dr_im/VenaV1.jpg', '2022-11-24 16:02:13', 'admin', '2022-11-24 16:14:32', 'admin'),
(1404, 'พญ.ธัญนุช โอปณะโสภิต', 'เวชศาสตร์ครอบครัว', '', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์ - วันศุกร์ เวลา 08.00 - 16.00 น.', '', '', 'dr_im/nonpicw.jpg', '2022-11-24 16:05:24', 'admin', '2022-11-24 16:14:58', 'admin'),
(1405, 'พญ.จตุรพร คติบัญชา', 'เวชศาสตร์ครอบครัว', '', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการพิเศษ', '', '', '', '', '', '', '', '', '', '', '', 'วันจันทร์ - วันศุกร์ เวลา 08.00 - 16.00 น.', '', '', 'dr_im/nonpicw.jpg', '2022-11-24 16:06:05', 'admin', '2023-04-20 11:42:20', 'admin'),
(1406, 'พญ.สุมัจฉา ยอดบุญมา', 'เวชศาสตร์ครอบครัว', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'นายแพทย์ชำนาญการ', '', '', '', '', '', '', '', '', '', '', '', 'วันจันทร์ - วันศุกร์ เวลา 08.00 - 16.00 น.', '', '', 'dr_im/SumatV1.jpg', '2023-04-20 11:43:39', 'admin', '2023-04-20 12:01:26', 'admin'),
(1407, 'พญ.จุฑามาศ วงศ์เทววิมาน', 'เวชศาสตร์ครอบครัว', '', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์ - วันศุกร์ เวลา 08.00 - 16.00 น.', '', '', 'dr_im/nonpicw.jpg', '2022-11-24 16:06:31', 'admin', '2022-11-24 16:15:19', 'admin'),
(1408, 'พญ.วรัญญา ตั้งตระกูล', 'เวชศาสตร์ครอบครัว', '', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'วันจันทร์ - วันศุกร์ เวลา 08.00 - 16.00 น.', '', '', 'dr_im/nonpicw.jpg', '2022-11-24 16:07:19', 'admin', '2022-11-24 16:15:09', 'admin'),
(1409, 'นพ.วุฒิไกร กรพิมาย', 'เวชศาสตร์ครอบครัว', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการพิเศษ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/VutikV1.jpg', '2025-10-09 10:29:50', 'admin', NULL, NULL),
(1410, 'นพ.โกสินทร์ มหรรณพกุล', 'เวชศาสตร์ครอบครัว', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpic.jpg', '2025-10-09 10:30:55', 'admin', NULL, NULL),
(1411, 'นพ.ศิวกร จัดระเบียบ', 'เวชศาสตร์ครอบครัว', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpic.jpg', '2025-10-09 10:31:31', 'admin', NULL, NULL),
(1412, 'พญ.มัลลิกา ธาราธิคุณ', 'เวชศาสตร์ครอบครัว', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ชำนาญการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/MalliV1.jpg', '2025-10-09 10:32:12', 'admin', NULL, NULL),
(1501, 'พญ.ดุษฎีพร จันปัญญา', 'Fammed', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ปฏิบัติการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpicw.jpg', '2025-10-09 10:44:40', 'admin', NULL, NULL),
(1502, 'นพ.ธนดล เวณุนันท์', 'Fammed', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ปฏิบัติการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpic.jpg', '2025-10-09 10:44:40', 'admin', NULL, NULL),
(1503, 'นพ.นิติพงศ์ พงษ์สาครสวัส', 'Fammed', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ปฏิบัติการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpic.jpg', '2025-10-09 10:44:40', 'admin', NULL, NULL),
(1504, 'พญ.อารียา คิม', 'Fammed', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ปฏิบัติการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpicw.jpg', '2025-10-09 10:44:40', 'admin', NULL, NULL),
(1505, 'พญ.กนกพร จันทร์เมือง', 'Fammed', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ปฏิบัติการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpicw.jpg', '2025-10-09 10:44:40', 'admin', NULL, NULL),
(1506, 'นพ.วริทธิ์ อิทธิพันธุวัฒน์', 'Fammed', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ปฏิบัติการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpic.jpg', '2025-10-09 10:44:40', 'admin', NULL, NULL),
(1507, 'นพ.ชิษณุพงศ์ พรหมเมืองขวา', 'Fammed', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ปฏิบัติการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpic.jpg', '2025-10-09 10:44:40', 'admin', NULL, NULL),
(1508, 'พญ.ณัฐชยา เลขานุกิจ', 'Fammed', 'วุฒิบัตรสาขาเวชศาสตร์ครอบครัว', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'นายแพทย์ปฏิบัติการ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dr_im/nonpicw.jpg', '2025-10-09 10:44:40', 'admin', NULL, NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
